name: Build
on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install Theos
      run: |
        export THEOS=~/theos
        echo "THEOS=$THEOS" >> $GITHUB_ENV
        echo "THEOS_MAKE_PATH=$HOME/theos/makefiles" >> $GITHUB_ENV
        git clone --recursive https://github.com/theos/theos.git $THEOS
        brew install ldid xz
    - name: Install SDK
      run: |
        mkdir -p ~/theos/sdks
        curl -L "https://github.com/theos/sdks/archive/refs/heads/master.tar.gz" -o sdks.tar.gz
        tar -xzf sdks.tar.gz --strip-components=1 -C ~/theos/sdks/ "sdks-master/iPhoneOS16.5.sdk"
    - name: Build
      run: make
    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: HelloNeighborTweak-dylib
        path: .theos/obj/**/*.dylib
